spring:
  application:
    name: marln-user-service

  datasource:
    platform: postgres
    url: jdbc:postgresql://marln-trial-database.c5ew6uekogft.me-central-1.rds.amazonaws.com:5432/postgres
    username: marlntrial
    password: Mangaldoi#25
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_data
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: user_data  # Only specify what's different
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true
server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-40-172-116-146.me-central-1.compute.amazonaws.com:8761/eureka

logging:
  file:
    name: /var/log/app/user.log
